[package]
name = "core-lib"
version = "0.1.0"
authors = ["sunaemon <@sunaemon0>"]
workspace = ".."

[dependencies]
nom = "^2.1"
subprocess = "*"
log = "*"
env_logger = "*"
rustc-serialize = "^0.3.0"
combine = "2.3.1"
clippy = {version = "*", optional = true}

[features]
default = []

